// generated by stringer -type=shipId; DO NOT EDIT

package main

import "fmt"

const _shipId_name = "OceanAircraftCarrierBattleshipSubmarineDestroyerCruiserPatrolBoat"

var _shipId_index = [...]uint8{0, 5, 20, 30, 39, 48, 55, 65}

func (i shipId) String() string {
	if i < 0 || i+1 >= shipId(len(_shipId_index)) {
		return fmt.Sprintf("shipId(%d)", i)
	}
	return _shipId_name[_shipId_index[i]:_shipId_index[i+1]]
}
